config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#home"

  get '/signup'       , to: 'users#new'

  get '/login'        , to: "sessions#new"
  post '/login'       , to: "sessions#create"
  delete '/logout'    , to: "sessions#destroy" 
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :tags
  resources :questions 
  
  resources :quizzes, only: [:index, :new, :create, :show, :update, :destroy] do
    member do
      get "restart"
      get "continue"
      get "scoring"
      get "back"
    end
    resources :lists, only: [:new, :update, :create, :show] 

  end
  resources :rankings, only: [:index]


end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  has_many :q_tags, dependent: :destroy
  has_many :tags, through: :q_tags
  has_one_attached :image
  has_many :q_similars, dependent: :destroy
  has_many :question_lists, dependent: :destroy
  has_many :lists, through: :question_lists
  
  accepts_nested_attributes_for :q_similars, allow_destroy: true
  accepts_nested_attributes_for :q_tags, allow_destroy: true

  validates :title, presence: true
  validates :mean, presence: true

  def display_image
    image.variant(resize_to_limit: [100,100])
  end

  # def self.search(question)
  #   where(["title like? OR mean like?", "%#{keyword}%", "%#{keyword}%"])
  # end
end

app/controllers/questions_controller.rb
require 'csv'
class QuestionsController < ApplicationController
  before_action :set_questions, only: [:edit, :update, :destroy, :search]
  before_action :correct_user, only: [:edit, :destroy]

  def index
    @tags = Tag.all.order('id ASC')
    @tag_id = params[:tag]
    @questions = Question.page(params[:page]).per(7).order('id ASC')
    # @questions = Question.all.order('id ASC')
    @questions = @questions.where('title LIKE ? ', "%#{params[:search]}%").
                 or(@questions.where('mean LIKE ? ', "%#{params[:search]}%")) if params[:search].present?
   

    respond_to do |format|
      format.html
      format.csv do |csv|
        @questions = Question.all
        send_posts_csv(@questions)
      end
    end
  end

  def new
    @question = Question.new
    @question.q_similars.build
    @question.q_tags.build
  end

  def create
    @question = Question.new(question_params)
    @question.image.attach(params[:question][:image])
    
    if @question.save
      flash[:alert] = "Word is saved"
      redirect_to questions_path
    else
      flash[:alert] = "Word is not saved"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @question.update(question_params)
    redirect_to questions_path
  end

  def destroy
    @question.destroy
    redirect_to questions_path, status: :see_other
  end


  private

  def set_questions
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :mean, :image, q_similars_attributes: [:id, :similar_word, :_destroy], 
                                                            q_tags_attributes: [:id, :tag_id, :destroy]).merge(user_id: session[:user_id])
  end

  def send_posts_csv(questions)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      column_names = %w[Word Mean]
      csv << column_names
      questions.each do |question|
        column_values = [
          question.title,
          question.mean
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "投稿一覧.csv")
  end

  def correct_user
    redirect_to(questions_path, status: :see_other) unless @question.user.id == current_user.id
  end


end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label "Word" %>
        <%= f.text_field :title, placeholder: "title", class: "field" %>
        
        <%= f.label :mean %>
        <%= f.text_field :mean, placeholder: "mean", class: "field" %>
        
        <%= f.label "Photo" %>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class:"file-field" %>


        
          
        <div id="detail-association-insertion-point" > 
          <%= f.fields_for :q_similars do |q_similar| %>
            <div>
              <%= render 'q_similar_fields', f: q_similar %>
            </div>
          <% end %>
        </div>
       
        <div class = "add-box">
          <%= link_to_add_association "Add", f, :q_similars, id: 'add-btn', data: {
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'after' } %>
        </div>
        
        <%= f.fields_for :q_tags do |q_tag| %>
          <div>
            <%= render 'q_tag_form', f: q_tag %>
          </div>
        <% end %>  
        
        
        <div><%= f.submit "Save", id: "btn" %></div>
<% end %>

app/views/questions/_q_similar_fields.html.erb
<div class = "nested-fields">
  <div class="s-w-wrap">
    <%= f.label "Similar Words", id: "similar-label" %>
    <%= f.text_field :similar_word, class: "similar-field" %>
    <%= link_to_remove_association "Delete", f, id: "del-btn" %> 
  </div> 
</div>

app/views/questions/_q_tag_form.html.erb
<div>
  <%= f.label "Tag" %>
  <%= f.collection_select :tag_id, Tag.all, :id, :name %>
</div>

app/views/questions/edit.html.erb
<div class="form-wrap" id = "small-page" >
  <h1 class = "name1">Edit</h1>
  
  <div class ="in-form">
    <%= render 'form' %>

  </div>
  <div id = "index-btn"><%= link_to "Go to List", questions_path %></div>
</div>
</div>

app/views/questions/index.html.erb
<p class="alert-save alert"><%= alert %></p>

<div class="form-wrap" id="big-page">
  <h1 class="name1">Words</h1>
  <div class = "in-form">
  <%# <% if logged_in? %> 
    <div id="new-btn"><%= link_to "Create New Word", new_question_path %></div>
  <%# <% end %> 
  <%= form_with url: questions_path, local: true, method: :get do |f| %>
  
  
  <table class = "in-form">
    <thead>
      <tr>
        <th>no</th>
        <th>Word</th>
        <th>Mean</th>
        <th>Photo</th>
        <th style="width:200px;">Similar Words</th>
        <th>
          Tag
          <%# <%= f.collection_select :tag_id, Tag.all, :id, :name %> 
        </th>
        
          <div class="search-form">
            <%= f.submit "search",class:"search-btn" %>
            <%= f.search_field :search, placeholder: "Search", class: "search-field" %>
          </div>
        
      </tr>
    </thead>
    <% end %>
    <tbody class = "words-tags-table">
        <% @questions.each do |question| %>
          <tr>
            <td style="color:rgb(68, 151, 224); font-weight:700;"><%= question.id %></td>
            <td style ="font-weight:700"><%= question.title %></td>
            <td><%= question.mean %></td>
            <td> 
                <% if question.image.attached? %>
                  <%= image_tag question.display_image %>
                <% end %>
            </td>
            <td>
              <% question.q_similars.each do |similar| %>
                <li><%= similar.similar_word %></li>
              <% end %>
            </td>
            <% question.tags.each do |tag|%>
            <td>
              <%= tag.name %>
            </td>
            <% end %>
            <% if logged_in? %>  
              <% if current_user.id == question.user_id %>
                <td style="width:100px;"><%= link_to "Edit", edit_question_path(question.id), id:"btn-to-edit" %></td>
                <td style="width:100px;"><%= button_to "Delete", question_path(question.id), method: :delete, id:"btn-to-del" %></td>
              <% end %> 
            <% end %> 
          </tr>
        <% end %> 
    </tbody>
  </table>
    <div id="index-btn"><%= link_to "Print CSV", questions_path(format: :csv) %></div>
    <div id="paginate-wrap">
      <%= paginate @questions %>
    </div>
  </div>
    
    
</div>

app/views/questions/new.html.erb
<div class="form-wrap" id ="small-page">
  <h1 class = "name1" >New Word</h1>
    <div class="in-form">
      <%= render 'form' %>
      <div id="index-btn"><%= link_to 'Go to List', questions_path %></div>      
    </div>
  </div>
</div>

app/views/questions/search.html.erb
<div class="form-wrap" id="big-page">
  <h1 class="name1">Words</h1>
  <div id="new-btn"><%= link_to "Create New Word", new_question_path %></div>

  <div class="search-form">
      <%= form_with url: search_questions_path, local: true, method: :get do |f| %>
        <%= f.submit class:"search-btn" %>
        <%= f.text_field :word, placeholder: "Search", class: "search-field" %>
        <%= f.select :search, options_for_select([["word"],["mean"],["tag"]]), class: "tag-select"%>
      <%end%>
  </div>

  <table class = "in-form">
    <thead>
      <tr>
        <th>no</th>
        <th>Word</th>
        <th>Mean</th>
        <th>Photo</th>
        <th style="width:200px;">Similar Words</th>
        <th>Tag</th> 
      </tr>
    </thead>
    <tbody class = "words-tags-table">
      <% @questions.each do |question| %>
        <tr>
          <td style="color:rgb(68, 151, 224); font-weight:700;"><%= question.id %></td>
          <td style ="font-weight:700"><%= question.title %></td>
          <td><%= question.mean %></td>
          <td> 
              <% if question.image.attached? %>
                <%= image_tag question.display_image %>
              <% end %>
           
          </td>
          <td>
            <% question.q_similars.each do |similar| %>
              <li><%= similar.similar_word %></li>
            <% end %>
          </td>
          <% question.tags.each do |tag|%>
          <td>
            <%= tag.name %>
          </td>
          <% end %>  
          <% if current_user.id == question.user_id %>
            <td style="width:100px;"><%= link_to "Edit", edit_question_path(question.id), id:"btn-to-edit" %></td>
            <td style="width:100px;"><%= button_to "Delete", question_path(question.id), method: :delete, id:"btn-to-del" %></td>
          <% end %> 
        </tr>
      <% end %>   
    </tbody>
  </table>
    <div id="index-btn"><%= link_to "Print CSV", questions_path(format: :csv) %></div>
    <div id="paginate-wrap">
      <%= paginate @questions %>
    </div>
    
</div>