config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#home"

  get '/signup'       , to: 'users#new'

  get '/login'        , to: "sessions#new"
  post '/login'       , to: "sessions#create"
  delete '/logout'    , to: "sessions#destroy" 
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :tags
  resources :questions 
  
  resources :quizzes, only: [:index, :new, :create, :show, :update, :destroy] do
    member do
      get "restart"
      get "continue"
      get "scoring"
      get "back"
    end
    resources :lists, only: [:new, :update, :create, :show] 

  end
  resources :rankings, only: [:index]


end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :q_tags, dependent: :destroy
  has_many :questions, through: :q_tags
  belongs_to :user, optional: true
  validates :name, uniqueness: true, presence: true
  
  # def self.looks(search, word)
  #   p 111111111
  #   p search
  #   p word
  #   @title = Question.where("title LIKE?","%#{word}%")
  # end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # before_action :logged_in_user,  only: [:index, :edit, :update]
  before_action :set_tag,         only: [:edit, :update, :destroy, :search]
  before_action :correct_user,    only: [:edit, :destroy]
  
  def index
    @tags = Tag.all.order('id ASC')
    @tags = @tags.where('name LIKE ?', "%#{params[:tag]}%") if params[:tag].present?
  end

  def new
    @tag = Tag.new
  end

  def show
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:alert] = "Tag is saved"
      redirect_to tags_path
    else
      flash[:alert] = "Tag is not saved"
      render 'new', status: :unprocessable_entity
    end
   
  end

  def edit
  end

  def update
    @tag.update(tag_params)
    redirect_to tags_path
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end


  def tag_params
    params.require(:tag).permit(:name).merge(user_id: session[:user_id])
  end

  def correct_user
    redirect_to(tags_path, status: :see_other) unless @tag.user.id == current_user.id
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<div class="form-wrap" id="small-page">
  <div class="in-form">
    <h1 class="name1">Edit</h1>
    <%= form_with model: @tag do |f| %>
    <%= f.text_field :name, class: "field" %>
    <%= f.submit "Update Tag", id: "btn" %>
    <% end %>
    <%= link_to "Go to Tag List", tags_path, id: "index-btn" %>
  </div>
</div>

app/views/tags/index.html.erb
  <p class="alert-save alert"><%= alert %></p>

<div class="form-wrap" id = "small-page">
    <div class = "in-form">
    <h1 class="name1">Tags</h1>

    <table class = "in-form">   
      <thead>
        <tr>
          <th>no</th>
          <th colspan = "3">tag</th>
          <div class="search-form">          
            <%= form_with url: tags_path, local: true, method: :get do |f| %>
              <%= f.submit "search", class: "search-btn"%>
              <%= f.text_field :tag, class: "search-field", placeholder: "Search" %>
            <%end%>
          </div> 

        </tr>
      </thead>
      <tbody class = "words-tags-table">
      <% @tags.each do |t| %>
        <tr>
          <td style = "color:rgb(68, 151, 224); font-weight:700"><%= t.id%></td>
          <td><%= t.name %></td>
          <% if logged_in? %>
            <% if current_user.id == t.user_id %>
              <td><%= link_to "Edit", edit_tag_path(t.id), id: "btn-to-edit" %></td>
              <td><%= button_to "Delete", tag_path(t.id), method: :delete, id: "btn-to-del" %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
      <%= link_to "Create New Tag", new_tag_path, id:"index-btn" %>
  </div>
</div>

app/views/tags/new.html.erb
<div class="form-wrap" id="small-page">
  <div class="in-form">
    <h1 class="name1">New Tag</h1>
    <%= form_with model: @tag do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_field :name, placeholder: "tag", class: "field" %>
      <%= f.submit "Create", id: "btn" %>
    <% end %>
    <%= link_to "Go to Tag List", tags_path, id: "index-btn" %>
  </div>
</div>