config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#home"

  get '/signup'       , to: 'users#new'

  get '/login'        , to: "sessions#new"
  post '/login'       , to: "sessions#create"
  delete '/logout'    , to: "sessions#destroy" 
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :tags
  resources :questions 
  
  resources :quizzes, only: [:index, :new, :create, :show, :update, :destroy] do
    member do
      get "restart"
      get "continue"
      get "scoring"
      get "back"
    end
    resources :lists, only: [:new, :update, :create, :show] 

  end
  resources :rankings, only: [:index]


end

app/views/layouts/_header.html.erb
<header>
        <div class="head">
            <div class="voca"><%= link_to "Voca Note", root_path %></div>
              <ul id = "top-menu"> 
                <% if logged_in? %>
                  <li><%= link_to "Log out", logout_path, data: {"turbo-method": :delete} %></li>   
                  <li><%= link_to "Quiz", quizzes_path %></li>
                  <li><%= link_to "Words", questions_path %></li>
                  <li><%= link_to "Tags", tags_path %></li>

                <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                  <li><%= link_to "Sign up", signup_path %></li>
                <% end %>
                           
              </ul>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voca1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/header' %>
  </body>
</html>